# Generated by Django 4.1 on 2022-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='posts',
            field=models.ManyToManyField(blank=True, to='content.postmodel'),
        ),
    ]
